-- ============================================
-- Homework evidence: attempts + answers, and word-level scopes
-- ============================================
-- Migration 053 made homework a live read of vocab_bkt: the teacher saw
-- "done / not done" and nothing else. This adds the evidence behind it.
--
--   • v2_assignments.item_keys — an optional hand-picked selection inside the
--     scope (e.g. 12 words from Chapter 3). NULL = the whole scope.
--
--   • homework_attempts — one row per run a student starts from a homework
--     link. Its id is generated by the browser, so answers can reference it
--     before the row has been written. Tracks when it started, when the last
--     answer came in, how many were answered/correct and the active seconds
--     spent (time per question, capped so a tab left open doesn't count).
--
--   • homework_answers — every answer given in a homework attempt: the item,
--     what the student gave, right or wrong, and how long it took.
--
-- Teachers (owners and co-teachers, via my_v2_taught_class_ids() from 081)
-- read both for their classes' assignments. Students write and read their own.

ALTER TABLE v2_assignments ADD COLUMN IF NOT EXISTS item_keys TEXT[];

COMMENT ON COLUMN v2_assignments.item_keys IS
'Optional hand-picked items (headwords / question ids) within the scope. NULL means the whole chapter range or topic.';

CREATE TABLE IF NOT EXISTS homework_attempts (
    id             UUID PRIMARY KEY,                 -- generated client-side
    assignment_id  UUID NOT NULL REFERENCES v2_assignments(id) ON DELETE CASCADE,
    student_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_answer_at TIMESTAMPTZ,
    answered       INTEGER NOT NULL DEFAULT 0 CHECK (answered >= 0),
    correct        INTEGER NOT NULL DEFAULT 0 CHECK (correct >= 0),
    active_seconds INTEGER NOT NULL DEFAULT 0 CHECK (active_seconds >= 0)
);

CREATE INDEX IF NOT EXISTS idx_homework_attempts_assignment
    ON homework_attempts (assignment_id, student_id, started_at DESC);

CREATE TABLE IF NOT EXISTS homework_answers (
    id            BIGSERIAL PRIMARY KEY,
    attempt_id    UUID NOT NULL REFERENCES homework_attempts(id) ON DELETE CASCADE,
    assignment_id UUID NOT NULL REFERENCES v2_assignments(id) ON DELETE CASCADE,
    student_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_key      TEXT NOT NULL,
    response      TEXT,                              -- typed text or chosen option
    correct       BOOLEAN NOT NULL,
    mode          TEXT,                              -- 'mc' | 'type' | 'self'
    ms            INTEGER,                           -- time on the question
    answered_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_homework_answers_attempt
    ON homework_answers (attempt_id, answered_at);
CREATE INDEX IF NOT EXISTS idx_homework_answers_assignment
    ON homework_answers (assignment_id, student_id);

ALTER TABLE homework_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE homework_answers  ENABLE ROW LEVEL SECURITY;

-- Students: their own rows, and only for homework set to one of their classes
-- (v2_assignments RLS already limits the subquery to those).
DROP POLICY IF EXISTS "Students manage own homework attempts" ON homework_attempts;
CREATE POLICY "Students manage own homework attempts"
ON homework_attempts FOR ALL
TO authenticated
USING      (student_id = auth.uid())
WITH CHECK (student_id = auth.uid() AND assignment_id IN (SELECT id FROM v2_assignments));

DROP POLICY IF EXISTS "Students manage own homework answers" ON homework_answers;
CREATE POLICY "Students manage own homework answers"
ON homework_answers FOR ALL
TO authenticated
USING      (student_id = auth.uid())
WITH CHECK (student_id = auth.uid() AND assignment_id IN (SELECT id FROM v2_assignments));

-- Teachers and co-teachers: read everything for their classes' homework.
DROP POLICY IF EXISTS "Teachers read homework attempts" ON homework_attempts;
CREATE POLICY "Teachers read homework attempts"
ON homework_attempts FOR SELECT
TO authenticated
USING (assignment_id IN (
    SELECT id FROM v2_assignments WHERE class_id IN (SELECT my_v2_taught_class_ids())));

DROP POLICY IF EXISTS "Teachers read homework answers" ON homework_answers;
CREATE POLICY "Teachers read homework answers"
ON homework_answers FOR SELECT
TO authenticated
USING (assignment_id IN (
    SELECT id FROM v2_assignments WHERE class_id IN (SELECT my_v2_taught_class_ids())));

COMMENT ON TABLE homework_attempts IS
'One row per homework run a student starts from a homework link: timing, answered/correct counts and active seconds.';
COMMENT ON TABLE homework_answers IS
'Every answer given during a homework attempt: item, response, right/wrong, time taken.';
